Trial/Areas/Admin/Controllers/HomeAdminController.cs
using Microsoft.Ajax.Utilities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Xml.Linq;
using Trial.App_Start;
using Trial.Models;

namespace Trial.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        // GET: Admin/HomeAdmin

        dbFinalTermDataContext db = new dbFinalTermDataContext();
        public ActionResult Index()
        {
            if (Session["User"] == null)
            {
                System.Diagnostics.Debug.WriteLine("Is null");
                return RedirectToAction("FirstPage","HomePage");
            }
            return View();
        }




        /*List of users*/
        [AdminAuthorize(idFeature = 1)]
        public ActionResult ListOfUsers(int? size, int? page, string account = "", string position = "", int isBlocked = 0)
        {
            ViewBag.pos = position;
            var users_list = from user in db.users
                             where user.email.Contains(account) && user.position.Contains(position) && !user.email.Contains("admin")
                             && user.isBlocked.Equals(isBlocked)
                             select new userTable
                             { 
                                 id = user.user_id,
                                 email = user.email,
                                 full_name = user.user_fname,
                                 position = user.position,
                                 is_blocked = (int)user.isBlocked
                             };
            int pageSize = (size ?? 5);
            int pageNum = page ?? 1;
            return View(users_list.ToPagedList(pageNum, pageSize));
        }



        [AdminAuthorize(idFeature = 3)]
        public ActionResult User_Detail(int id, string position) 
        {
            int numOfProj = 0;
            if (position.Contains("Applicant")) {
                numOfProj = (from users in db.users
                            join CV_manager in db.CV_managers
                            on users.user_id equals CV_manager.user_id
                            where users.user_id == id
                            join CV in db.CVs
                            on CV_manager.CV_id equals CV.CV_id
                            select CV).Count();

            }
            else
            {
                numOfProj = (from users in db.users
                            join JD_manager in db.JD_managers
                            on users.user_id equals JD_manager.user_id
                             where users.user_id == id
                             join JD in db.JDs
                            on JD_manager.JD_id equals JD.JD_id
                            select JD).Count();
            }
            ViewBag.numProj = numOfProj;
            var user = db.users.Where(model => model.user_id == id).FirstOrDefault();
            return View(user);
        }


        [AdminAuthorize(idFeature = 5)]
        public ActionResult Block_UnBlock(int id)
        {
            
            var blocked_user = db.users.First(user => user.user_id == id);
            string mailForNoti = System.IO.File.ReadAllText(Server.MapPath("~/Content/mail/mail.html"));
            string mailForNoti2 = System.IO.File.ReadAllText(Server.MapPath("~/Content/mail/mail2.html"));
            //Hasnt been blocked
            if (blocked_user.isBlocked == 0)
            {
                blocked_user.isBlocked = 1;
                Trial.Common.Common.SendMail("JOB SEEKER", "USER #" + blocked_user.user_id.ToString(), mailForNoti, blocked_user.email);

            }
            //Has been blocked
            else if (blocked_user.isBlocked == 1)
            {
                blocked_user.isBlocked = 0;
                Trial.Common.Common.SendMail("JOB SEEKER", "USER #" + blocked_user.user_id.ToString(), mailForNoti2, blocked_user.email);
            }
            UpdateModel(blocked_user);
            db.SubmitChanges();
            return RedirectToAction("ListOfUsers", new { @isBlocked = 1 });
        }



        [AdminAuthorize(idFeature = 2)]
        /*List of post*/
        public ActionResult ListOfPosts(int? size, int? page, string category = "", string account = "",  string status = "Wait for justify")
        {

            var CVposts_list = (from CV_manager in db.CV_managers
                                join user in db.users
                                on CV_manager.user_id equals user.user_id
                                where user.email.Contains(account)
                                join CV in db.CVs
                                on CV_manager.CV_id equals CV.CV_id
                                where CV.status.Contains(status)
                                select new AdminListPosts
                                {
                                    id = CV.CV_id,
                                    email = user.email,
                                    name = CV.applicant_name,
                                    category = "CV",
                                    upload_date = CV.date_upload.ToShortDateString(),
                                    status = CV.status,
                                }).ToList().OrderByDescending(model => model.upload_date);
/*            System.Diagnostics.Debug.WriteLine("items: " + CVposts_list.Count);
            foreach (var item in CVposts_list)
            {
                System.Diagnostics.Debug.WriteLine("item: " + item);
            }*/


            var JDposts_list = (from JD_manager in db.JD_managers
                                join user in db.users
                                on JD_manager.user_id equals user.user_id
                                where user.email.Contains(account)
                                join JD in db.JDs
                                on JD_manager.JD_id equals JD.JD_id
                                where JD.status.Contains(status)
                                select new AdminListPosts
                                {
                                    id = JD.JD_id,
                                    email = user.email,
                                    name = JD.company_name,
                                    category = "JD",
                                    upload_date = JD.date_upload.ToShortDateString(),
                                    status = JD.status,
                                }).ToList().OrderByDescending(model => model.upload_date);
            /*            System.Diagnostics.Debug.WriteLine("items2: " + JDposts_list.Count);
                        foreach (var item in JDposts_list)
                        {
                            System.Diagnostics.Debug.WriteLine("item2: " + item);
                        }*/
            ViewBag.mode = category;
            int pageSize = (size ?? 6);
            int pageNum = page ?? 1;
            if (category.Equals("Curriculum Vitae"))
            {
                /*ViewBag.mode = "Curriculum Vitae";*/
                return View(CVposts_list.ToPagedList(pageNum, pageSize));
            }
            else if (category.Equals("Job Description"))
            {
                /*ViewBag.mode = "Job Description";*/
                return View(JDposts_list.ToPagedList(pageNum, pageSize));
            }
            /*ViewBag.mode = "";*/
            var res = CVposts_list.Union(JDposts_list).ToList();
            return View(res.ToPagedList(pageNum, pageSize));
        }


        [AdminAuthorize(idFeature = 4)]

        public ActionResult Post_Detail_CV(int id)
        {
            var CV = db.CVs.Where(model => model.CV_id == id).First();
            return View(CV);
                
        }



        [AdminAuthorize(idFeature = 4)]
        public ActionResult Post_Detail_JD(int id)
        {
            var JD = db.JDs.Where(model => model.JD_id == id).First();
            return View(JD);

        }




        public ActionResult GetPDF(string directory)
        {
            System.Diagnostics.Debug.WriteLine(directory);
            string filepath = "~" + directory;
            return File(filepath, "application/pdf");
        }



        [AdminAuthorize(idFeature = 6)]
        public ActionResult Post_Justify(int id, string category, string status)
        {
            System.Diagnostics.Debug.WriteLine(status);
            if (category.Equals("CV")) {
                var postCV = db.CVs.First(CV => CV.CV_id == id);
                postCV.status = status;
                UpdateModel(postCV);
                db.SubmitChanges();
                if (status.Contains("Approved")) {
                    return RedirectToAction("ListOfPosts", new { @status = "Approved" });
                }
                else
                {
                    return RedirectToAction("ListOfPosts", new { @status = "Rejected" });
                }
                
            }
            else
            {
                var postJD = db.JDs.First(JD => JD.JD_id == id);
                postJD.status = status;
                UpdateModel(postJD);
                db.SubmitChanges();
                if (status.Contains("Approved"))
                {
                    return RedirectToAction("ListOfPosts", new { @status = "Approved" });
                }
                else
                {
                    return RedirectToAction("ListOfPosts", new { @status = "Rejected" });
                }
            }
        }


        public ActionResult AccessDenied()
        {
            return View();
        }

        [AdminAuthorize(idFeature = 7)]
        public ActionResult SendMail(string email)
        {
            ViewBag.Email = email;  
            return View();
        }
        
        
        [HttpPost]
        public ActionResult SendMail(FormCollection form)
        {
            string toEmailChanged = form["toEmail"];

Trial/Areas/Admin/Views/HomeAdmin/AccessDenied.cshtml
@{
    Layout = null;
}

<!doctype html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Job Seeker | Blocked page</title>
    <meta name="description" content="Saleh Riaz - UI/UX Engineer. Designer. Computer Scientist">
    <meta name="keywords" content="ui engineer, ux, saleh, riaz, qureshi, website, softwares, salehriaz, salehriazq, computer scientist, design, visual design, saleh riaz qureshi" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Content/404page.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</head>
<body class="bg-purple">

    <div class="stars">
        <div class="custom-navbar">
            <div class="brand-logo" style="color:white">
                JOB SEEKER
            </div>
            <div class="navbar-links">
                <ul>
                    <li><a href="#">If You Think This Is A Mistake? </a></li>
                    <li><a href="#" class="btn-request">Send A Request</a></li>
                </ul>
            </div>
        </div>
        <div class="central-body">
            @*<img class="image-404" src="~/Content/images/404.svg" width="300px">*@
            <div style="font-weight: 500; font-size: 60px; color:white">403 <br />ACCESS DENIED</div>
            <a href="@Url.Action("Index","HomeAdmin")" class="btn-go-home">GO BACK TO HOME ADMIN</a>
        </div>
        <div class="objects">
            <img class="object_rocket" src="~/Content/images/rocket.svg" width="40px">
            <div class="earth-moon">
                <img class="object_earth" src="~/Content/images/earth.svg" width="100px">
                <img class="object_moon" src="~/Content/images/moon.svg" width="80px">
            </div>
            <div class="box_astronaut">
                <img class="object_astronaut" src="~/Content/images/astronaut.svg" width="140px">
            </div>
        </div>
        <div class="glowing_stars">
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>

        </div>

    </div>

</body>
</html>

Trial/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Content/adminStyle.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Koulen&family=League+Spartan&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chathura:wght@800&display=swap" rel="stylesheet">
    <!-- <link rel = "icon" href = "/image/logo_snkhead.png" type = "image/x-icon"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css">
</head>
<body>
    <div id="header">
        <!-- logo button  -->
        <a href="#" class="logo">Job Seeker</a>
        <!-- header - bar  -->
        <div class="nav mt-12">
            <ul class="sub-nav">
                <li><a href="#">Home</a></li>
                <li>
                    @{
                        var cur_user = (Trial.Models.user)HttpContext.Current.Session["User"];
                        if (cur_user != null)
                        {
                            string name = cur_user.email;
                            <a>@name.Split('@')[0]</a>
                        }
                                }
                </li>
                <li><a>@Html.ActionLink("Log out", "Logout", "User", new { area = "" }, null)</a></li>
            </ul>
        </div>
    </div>
    <div class="main">
        <nav class="menu">
            <div class="iconMenu element">
                <i class="fa-solid fa-bars" style="color: black;"></i>
            </div>
            <div class="userContainer element">

                <div class="userList">
                    <i class="fa-solid fa-chevron-right i1" style="color: #ffffff;" onclick="moreOption(1)"></i>
                    <a href="@Url.Action("ListOfUsers","HomeAdmin")" 
                        data-for-tab="1">Users List</a>
                </div>
                <div class="blockedList hidden h1">
                    <a href="@Url.Action("ListOfUsers", "HomeAdmin", new { @isBlocked = 1 })" data-for-tab="2">Blocked List</a>

                </div>
            </div>
            <div class="postContainer element">

                <div class="postList">
                    <i class="fa-solid fa-chevron-right i2" style="color: #ffffff;" onclick="moreOption(2,3)"></i>
                    <a href="@Url.Action("ListOfPosts", "HomeAdmin")" data-for-tab="3">Posts List</a>
                </div>
                <div class="approvedList hidden h2">
                    <a href="@Url.Action("ListOfPosts", "HomeAdmin", new { @status = "Approved" })" data-for-tab="4">Approved List</a>

                </div>
                <div class="rejectedList hidden h3">
                    <a href="@Url.Action("ListOfPosts", "HomeAdmin", new { @status = "Rejected" })" data-for-tab="5">Rejected List</a>
                </div>

            </div>
        </nav>


        <div class="notiContainer">
            <div class="notiTitle">
                Notification
            </div>
            <hr>
            <div class="notiList">
                <ul>
                    <li>
                        <div class="noti_eleTitle">
                            Notification 1: <span>(15/10/2023)</span>
                        </div>
                        <div class="noti_eleContent">
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur.
                        </div>
                    </li>
                    <li>
                        <div class="noti_eleTitle">
                            Notification 2: <span>(15/10/2023)</span>
                        </div>
                        <div class="noti_eleContent">
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur.
                        </div>
                    </li>
                    <li>
                        <div class="noti_eleTitle">
                            Notification 3: <span>(15/10/2023)</span>
                        </div>
                        <div class="noti_eleContent">
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur.
                        </div>
                    </li>
                    <li>
                        <div class="noti_eleTitle">
                            Notification 4: <span>(15/10/2023)</span>
                        </div>
                        <div class="noti_eleContent">
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur. Montes sit in facilisis a risus egestas...
                            Lorem ipsum dolor sit amet consectetur.
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <script src="~/Scripts/adminJS.js"></script>
</body>    
</html>

Trial/Areas/Admin/Views/HomeAdmin/ListOfPosts.cshtml
@model PagedList.IPagedList<Trial.Models.AdminListPosts>
@using PagedList.Mvc;
@{
    Layout = null;
    var firstEle = Model.FirstOrDefault();
    string status = "";
    if (firstEle != null)
    {
        if (firstEle.status.Contains("Approved")) { status = "Approved"; }
        else if (firstEle.status.Contains("Rejected")) { status = "Rejected"; }
        else if (firstEle.status.Contains("Wait for justify")) { status = "Wait for justify"; }
    }
    else
    {
        status = "Wait for justify";

    }
}

<!DOCTYPE html>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Content/adminStyle.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Koulen&family=League+Spartan&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chathura:wght@800&display=swap" rel="stylesheet">
    <!-- <link rel = "icon" href = "/image/logo_snkhead.png" type = "image/x-icon"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css">
</head>
<body>
    <div id="header" >
        <!-- logo button  -->
        <a href="#" class="logo">Job Seeker</a>
        <!-- header - bar  -->
        <div class="nav mt-12">
            <ul class="sub-nav">
                <li><a href="#">Home</a></li>
                <li>
                    @{
                        var cur_user = (Trial.Models.user)HttpContext.Current.Session["User"];
                        if (cur_user != null)
                        {
                            string name = cur_user.email;
                            <a>@name.Split('@')[0]</a>
                        }
                    }
                </li>
                <li><a>@Html.ActionLink("Log out", "Logout", "User", new { area = "" }, null)</a></li>
            </ul>
        </div>
    </div>
    <div class="main">
        <nav class="menu">
            <div class="iconMenu element">
                <i class="fa-solid fa-bars" style="color: black;"></i>
            </div>
            <div class="userContainer element">

                <div class="userList">
                    <i class="fa-solid fa-chevron-right i1" style="color: #ffffff;" onclick="moreOption(1)"></i>
                    <a href="@Url.Action("ListOfUsers", "HomeAdmin")"
                       data-for-tab="1">Users List</a>
                </div>
                <div class="blockedList hidden h1">
                    <a href="@Url.Action("ListOfUsers", "HomeAdmin", new { @isBlocked = 1 })" data-for-tab="2">Blocked List</a>

                </div>
            </div>
            <div class="postContainer element">

                <div class="postList">
                    <i class="fa-solid fa-chevron-right i2" style="color: #ffffff;" onclick="moreOption(2,3)"></i>
                    <a href="@Url.Action("ListOfPosts", "HomeAdmin")" data-for-tab="3">Posts List</a>
                </div>
                <div class="approvedList hidden h2">
                    <a href="@Url.Action("ListOfPosts", "HomeAdmin", new { @status = "Approved" })" data-for-tab="4">Approved List</a>

                </div>
                <div class="rejectedList hidden h3">
                    <a href="@Url.Action("ListOfPosts", "HomeAdmin", new { @status = "Rejected" })" data-for-tab="5">Rejected List</a>
                </div>

            </div>
        </nav>

        <form class="searchBox" method="get"
              action="@Url.Action("ListOfPosts", "HomeAdmin")">
            <input type="text" class="searchBar" name="account" />
            <span style="pointer-events:none">Searching for account</span>
            <i class="fa-solid fa-magnifying-glass"></i>
            <input type="hidden" name="status" value="@status" />
            <input type="hidden" name="category" value="@ViewBag.mode" />
        </form>
        <div class="table-content">
            <input type="button" id="Employer_JD" value="Job Description" style="left: 30%;"
                   onclick="location.href='@Url.Action("ListOfPosts", "HomeAdmin",new {@category = "Job Description", @status = status})'" />
            <input type="button" id="Applicant_CV" value="Curriculum Vitae"
                   onclick="location.href='@Url.Action("ListOfPosts", "HomeAdmin",new {@category = "Curriculum Vitae", @status = status})'" />
            <div class="row">
                <div class="col-xs-12">
                    <div class="table-responsive" data-pattern="priority-columns">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Account</th>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr style="position: relative;">
                                        <td style="padding: 15px 8px;">@item.email</td>
                                        <td style="padding: 15px 8px;">@item.name</td>
                                        <td style="padding: 15px 8px;">@item.category</td>
                                        <td style="padding: 15px 8px;">@item.upload_date</td>
                                        <td style="padding: 15px 8px;">
                                            


                                            @{
                                                if (item.category == "CV")
                                                {
                                                    <input type="button" id="option" class="det" value="Detail"
                                                       onclick="location.href='@Url.Action("Post_Detail_CV", "HomeAdmin",
                                                        new {@id = item.id, @category = item.category})'" />
                                                }
                                                else 
                                                { 
                                                    <input type="button" id="option" class="det" value="Detail"
                                                        onclick="location.href='@Url.Action("Post_Detail_JD", "HomeAdmin",
                                                        new {@id = item.id, @category = item.category})'" />
                                                }
                                                
                                                if (!item.status.Contains("Approved"))
                                                {
                                                    <input type="button" id="option" class="apr" value="Approve"
                                                           onclick="location.href='@Url.Action("Post_Justify", "HomeAdmin",
                                                            new {@id = item.id, @category = item.category, @status = "Approved"})'" />
                                                }
                                                else
                                                { }
                                                
                                                if (!item.status.Contains("Rejected"))
                                                {
                                                    <input type="button" id="option" class="rej" value="Reject"
                                                           onclick="location.href='@Url.Action("Post_Justify", "HomeAdmin",
                                                            new {@id = item.id, @category = item.category, @status = "Rejected"})'" />

                                                }
                                                else
                                                { }
                                            }
                                            @*@Html.ActionLink("Blocked", "Block_UnBlock", new {@id = item.id},
                                                new {@id = "option", @class = "rej", @type = "button", @style = "margin-left: 14%;" });*@


                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        @*Number of products*@
        <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right" style="position: absolute; top: 92.5%; left: 90%; font-weight: 500; ">
            Page: @(Model.PageCount<Model.PageNumber? 0:Model.PageNumber)/@Model.PageCount
        </div>
    </div>
    @*pages*@

    <div class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("ListOfPosts", "HomeAdmin", new { page = page, @status = status, category = ViewBag.mode }))
    </div>
    <style>
        .pagination {
            width: fit-content;
            /*border: solid 1px black;*/
            height: 25px;
            border-radius: 5px;
            align-content: center;
            justify-content: center;
            position: absolute;
            top: 90%;
            left: 20%;
        }

            .pagination li {
                padding: 0 7px;
                margin-top: -2px;
                border: none;
                display: inline;
                /*            background-color: #c3c3c3;*/
            }

            .pagination a:hover {
                color: #b8b8b8;
            }

            .pagination a {
                padding: 0;
                font-size: 16px;
                text-decoration: none;
                color: black;
                font-weight: 500;
            }
    </style>
    <script src="~/Scripts/adminJS.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>