Trial/Areas/Applicant/Controllers/HomeApplicantController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Trial.Models;

namespace Trial.Areas.Applicant.Controllers
{
    public class HomeApplicantController : Controller
    {
        // GET: Applicant/HomeApplicant
        dbFinalTermDataContext db = new dbFinalTermDataContext();

        //Home
        public ActionResult ApplicantFirstPage()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
        //Button find job by CV --> View ChooseYourCVList --> Choose --> call JDlist(?id) --> call FindByMyCV(?id)
        //--> new position; new location --> JDlist(?position, ?location) --> new Job List 

        //Joblist
        public ActionResult JDlist(int? size, int? page, int id = 1, string position = "", string location = "", bool useFindJob = false)
        {
            
            if(useFindJob == true) { FindByMyCV(id, ref position, ref location); }
            position = position.Trim();
            ViewBag.pos = position;
            ViewBag.locate = location;
            System.Diagnostics.Debug.WriteLine(position + " " + location);
            var listJD = (from JD in db.JDs
                         where (JD.location.Contains(location) && JD.isOffered == 0
                         && JD.status.Contains("Approved")) && (JD.company_name.Contains(position) || JD.hired_position.Contains(position))
                         select JD).OrderByDescending(model => model.date_upload);
            int pageSize = (size ?? 8);
            int pageNum = page ?? 1;
            return View(listJD.ToPagedList(pageNum, pageSize));
        }

        //JobDetail
        public ActionResult DetailJob(int id)
        {
            var JD = db.JDs.Where(model => model.JD_id == id).First();
            return View(JD);
        }
        public ActionResult GetPDF(string directory)
        {
            System.Diagnostics.Debug.WriteLine(directory);
            string filepath = "~" + directory;
            return File(filepath, "application/pdf");
        }


        //CVlist<Choose/feature>
        public void FindByMyCV(int id, ref string position, ref string location)
        {
            System.Diagnostics.Debug.WriteLine(id);
            user cur_user = (user)Session["User"];
            var suitable_CV = (from CV in db.CVs
                               where CV.CV_id == id
                               select new
                               {
                                   CV.applied_position,
                                   CV.location
                               }).ToList();
            foreach (var item in suitable_CV)
            {
                position = item.applied_position;
                location = item.location;
                System.Diagnostics.Debug.WriteLine(position);
                System.Diagnostics.Debug.WriteLine(location);
            }
        }

        //CVlist<Choose/view>
        public ActionResult ChooseYourCVList(int? size, int? page, string position = "", string location = "")
        {
            ViewBag.pos = position;
            ViewBag.locate = location;
            user cur_user = (user)Session["User"];
            var list = (from CV_manager in db.CV_managers
                        join CV in db.CVs
                        on CV_manager.CV_id equals CV.CV_id
                        where (CV_manager.user_id == cur_user.user_id && CV.status.Contains("Approved") 
                        && CV.location.Contains(location)) && (CV.applied_position.Contains(position) || CV.CV_name.Contains(position))
                        select new YourCV{ 
                            CVid =  CV.CV_id,
                            CVname = CV.CV_name,
                            CVpos = CV.applied_position,
                            dateUpload = CV.date_upload.ToShortDateString(),
                            CVstatus = CV.status,
                            CVlocation = CV.location
                        }).ToList().OrderByDescending(model => model.dateUpload);
            int pageSize = (size ?? 8);
            int pageNum = page ?? 1;
            return View(list.ToPagedList(pageNum, pageSize));
        }



        //YourCVlist
        public ActionResult YourCVList(int? size, int? page, string position = "", string location = "")
        {
            ViewBag.pos = position;
            ViewBag.locate = location;
            user cur_user = (user)Session["User"];
            var list = (from CV_manager in db.CV_managers
                        join CV in db.CVs
                        on CV_manager.CV_id equals CV.CV_id
                        where (CV_manager.user_id == cur_user.user_id
                        && CV.location.Contains(location)) && (CV.applied_position.Contains(position) || CV.CV_name.Contains(position))
                        select new YourCV{ 
                            CVid =  CV.CV_id,
                            CVname = CV.CV_name,
                            CVpos = CV.applied_position,
                            dateUpload = CV.date_upload.ToShortDateString(),
                            CVstatus = CV.status,
                            CVlocation = CV.location
                        }).ToList().OrderByDescending(model => model.dateUpload);
            int pageSize = (size ?? 8);
            int pageNum = page ?? 1;
            return View(list.ToPagedList(pageNum, pageSize));
        }

        //CVdetail
        public ActionResult Detail(int id) {
            var CV = db.CVs.Where(model => model.CV_id == id).First();
            return View(CV);
        }

        public ActionResult Delete(int id)
        {
            var CV = db.CVs.Where(model => model.CV_id == id).First();
            var CVmanage = db.CV_managers.Where(model => model.CV_id == id).First();
            db.CV_managers.DeleteOnSubmit(CVmanage);
            db.SubmitChanges();
            db.CVs.DeleteOnSubmit(CV);
            db.SubmitChanges();
            return RedirectToAction("YourCVList");
        }

        public string ProcessUpload(HttpPostedFileBase fileImage)
        {
            System.Diagnostics.Debug.WriteLine("I'm in processUpload" + fileImage.ToString());
            if (fileImage == null)
            {
                System.Diagnostics.Debug.WriteLine("Is null");
                return " ";
            }
            /*            ViewBag.filePic = "/Content/image/" + fileImage.FileName.ToString();*/
            fileImage.SaveAs(Server.MapPath("~/Content/images/" + fileImage.FileName));
            return "/Content/images/" + fileImage.FileName;
        }

        //CVformEdit (reuse the view of add)
        public ActionResult Edit(int id)
        {
            var cur_CV = db.CVs.First(CV => CV.CV_id == id);
            return View(cur_CV);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection form)
        {
            var cur_CV = db.CVs.First(CV => CV.CV_id == id);
            var CV_nameChanged = form["CV_name"];
            var applicant_nameChanged = form["applicant_name"];
            var locationChanged = form["location"];
            var applied_positionChanged = form["applied_position"];
            var CV_fileChanged = form["CV_file"];

            cur_CV.CV_name = CV_nameChanged;
            cur_CV.applicant_name = applicant_nameChanged;
            cur_CV.location = locationChanged;
            cur_CV.applied_position = applied_positionChanged;
            cur_CV.CV_file = CV_fileChanged;
            cur_CV.date_upload = DateTime.Now;
            cur_CV.status = "Wait for justify";
            UpdateModel(cur_CV);
            db.SubmitChanges();
            return RedirectToAction("YourCVList");
        }


        //CVform
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(FormCollection form, CV cur_CV)
        {
            var CV_nameChanged = form["CV_name"];
            var applicant_nameChanged = form["applicant_name"];
            var locationChanged = form["location"];
            var applied_positionChanged = form["applied_position"];
            var CV_fileChanged = form["CV_file"];

            cur_CV.CV_name = CV_nameChanged;
            cur_CV.applicant_name = applicant_nameChanged;
            cur_CV.location = locationChanged;
            cur_CV.applied_position = applied_positionChanged;
            cur_CV.CV_file = CV_fileChanged;
            cur_CV.date_upload = DateTime.Now;
            cur_CV.status = "Wait for justify";
            db.CVs.InsertOnSubmit(cur_CV);
            db.SubmitChanges();
            return UpdateManageCV();
        }
        public ActionResult UpdateManageCV()
        {
            var model = db.CVs.OrderByDescending(s => s.CV_id).FirstOrDefault();
            CV_manager cV_Manager = new CV_manager();
            cV_Manager.CV_id = model.CV_id;
            user curUser = (user)Session["User"];
            cV_Manager.user_id = curUser.user_id;
            db.CV_managers.InsertOnSubmit(cV_Manager);
            db.SubmitChanges();
            return RedirectToAction("YourCVList");
        }
    }
}

Trial/Areas/Applicant/Views/HomeApplicant/Add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.5.0/remixicon.css" crossorigin="">
    <link rel="stylesheet" href="~/Content/Applicant access/access/css/cv.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/Applicant access/access/font/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Koulen&family=League+Spartan&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chathura:wght@800&display=swap" rel="stylesheet">
    <link rel="icon" href="/image/logo_snkhead.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>
<body>
    <div id="main">
        <div id="header">
            <!-- logo button -->
            <a href="#" class="logo">
                <div class="inner-headings">
                    <span>
                        Job-Seeker<br />
                        Full-Time <br />
                        Part-Time <br />
                        Freelancer <br />
                        Intership <br />
                        Temporary <br />
                    </span>
                </div>
            </a>
            <!-- header - bar -->
            <div class="nav mt-12 ">
                <ul class="sub-nav">
                    <li class="mt-12"><a href="#">@Html.ActionLink("Home", "ApplicantFirstPage", "HomeApplicant")</a></li>
                    <li class="mt-12"><a href="">@Html.ActionLink("Joblist", "JDlist", "HomeApplicant")</a></li>
                    <li class="mt-12"><a href="#">@Html.ActionLink("Your CV list", "YourCVList", "HomeApplicant")</a></li>
                    <li class="mt-12"><a href="#">@Html.ActionLink("Contact", "Contact", "HomeApplicant")</a></li>
                    <!-- job button -->
                    <button class="bbtn2"><a href="#">@Html.ActionLink("Want a Job", "Add", "HomeApplicant", new { @style = "color:#fff; text-decoration: none;" })</a></button>
                </ul>
                <!-- Log out statement -->
                <div class="log-out" style="margin-left:600px">
                    <!-- Name User -->
                    @{
                        var cur_user = (Trial.Models.user)HttpContext.Current.Session["User"];
                        if (cur_user != null)
                        {
                            string name = cur_user.email;
                            <p class="name-user">
                                @name.Split('@')[0]
                            </p>
                        }
                    }
                    <!-- Log out button -->
                    <div class="scene">
                        <div class="cube">
                            <span class="side top">
                                @Html.ActionLink("Are You Sure?", "Logout", "User", new { area = "" }, new { @style = "text-decoration: none; color: white;" })
                            </span>
                            <span class="side front">
                                <i class="fa-solid fa-right-from-bracket"> Log Out</i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- FORM -->
        <div class="form-name">
            <p>Create your CV</p>
        </div>
        <div class="formCV">
            @using (Html.BeginForm())
            {
                <form method="post">
                    <h2>Your CV</h2>
                    <label for="name">CV Name:</label>
                    <input type="text" id="name" name="CV_name" placeholder="Your CV name..." required>
                    <br>
                    <label for="email">Your Name:</label>
                    <input type="text" id="email" name="applicant_name" placeholder="Your full name..." required>
                    <br>
                    <label for="education">Apply Position:</label>
                    <input type="text" id="education" name="applied_position" placeholder="Your position......">
                    <br>
                    <div class="location">
                        <label class="local-name" for="lname">Location:</label>
                        <select name="location" id="location-job">
                            <option value="HCM">HCM</option>
                            <option value="Hanoi">Hanoi</option>
                        </select>
                    </div>
                    <label for="file" class="upfile">Upload your CV file here:</label>
                    <input type="file"  id="CV_file" class="upfile" accept=".pdf, image/*">
                    <input type="hidden" name="CV_file" id="directory"/>

                    @*<button class="mtn"><span>Submit</span></button>*@
                    <input type="submit" value="Submit" class="btn btn-default mtn" />
                </form>
            }
        </div>
    </div>


    <!-- Footer -->
    <div id="FooterPage">
        <footer>
            <div class="container text-center text-md-left col-third">
                <div class="footer-wrap">
                    <div class="about">
                        <img src="img/icon/company-logo.svg" alt="">
                        <p class=" py-4" style="font-weight: 500; margin-top: -33px;">About</p>
                        <p class="text-muted py-4">
                            Job-Seeker which can provide you with all the tools </br> needed to run an effcieint business remotely.
                        </p>
                        <div class="social-media">
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/facebook-icon.svg" alt=""></a>
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/instagram-icon.svg" alt=""></a>
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/linkedin-icon.svg" alt=""></a>
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/email-icon.svg" alt=""></a>
                        </div>
                    </div>

                    <div class="company  ">
                        <h6 class="fw-bold">Company</h6>
                        <p><a href="./contact.html">Contact</a></p>
                        <p><a href="">Blog</a></p>
                        <p><a href="">Services</a></p>
                        <p><a href="">FQA</a></p>
                    </div>

                    <div class="useful-links  ">
                        <h6 class="fw-bold">Useful links</h6>
                        <p><a href="">Terms of </a></p>
                        <p><a href="">Services</a></p>
                        <p><a href="">Privacy Policy</a></p>
                        <p><a href="">Documentation</a></p>
                        <p><a href="">Changelog</a></p>
                        <p><a href="">Components</a></p>
                    </div>

                    <div class="newsletter  ">
                        <h6 class="fw-bold">Have a Question?</h6>
                        <p><i class="fa-solid fa-location-dot"></i>203 Fake St. Mountain View, San Francisco, California, USA</p>
                        <p><i class="fa-solid fa-phone"></i> 84+ 0935459488</p>
                        <p><i class="fa-solid fa-envelope"></i> kienphongtran2003@gmail.com / buikhoa2015@gmail.com  </p>
                    </div>

                </div>
                <div class="copyright txtwhite">
                    <p>&copy; 2023 JOB-SEEKER | Created by Phong / Khoa</p>
                    <!--
                    This template is licenced under Attribution 3.0 (CC BY 3.0 PL),
                    You are free to: Share and Adapt. You must give appropriate credit, you may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
                    -->
                </div>
            </div>
        </footer>
    </div>
        <script>
            $(document).ready(function () {
                
                $('#CV_file').click(function () {
                    console.log("You Click");
                    $('#CV_file').change(function () {
                        console.log("You change");
                        if (window.FormData !== undefined) {

                            var fileUpload = $('#CV_file').get(0);
                            var files = fileUpload.files;
                            var formData = new FormData();
                            formData.append("fileImage", files[0]);
                            //formData.append("fileImage", files[0]);
                            /*for (var i = 0; i < files.length; i++) {
                                formData.append("fileImage", files[i]);
                            }*/
                            $.ajax(
                                {
                                    type: 'POST',
                                    url: '/HomeApplicant/ProcessUpload',
                                    contentType: false,
                                    processData: false,
                                    data: formData,
                                    success: function (urlImage) {
                                        console.log(urlImage);
                                        $('#directory').attr('value', urlImage);
                                        $('#picture').val(urlImage);
                                    },
                                    error: function (err) {
                                        alert('Error ', err.statusText);
                                    }
                                });
                        }
                    });

                });
                
            });
        </script>
</body>
</html>