Trial/Areas/Employer/Controllers/HomeEmployerController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Trial.Models;
using static System.Net.Mime.MediaTypeNames;

namespace Trial.Areas.Employer.Controllers
{
    public class HomeEmployerController : Controller
    {
        // GET: Employer/HomeEmployer
        dbFinalTermDataContext db = new dbFinalTermDataContext();



        public ActionResult EmployerFirstPage()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }


        public ActionResult CVlist(int? size, int? page, int id = 1, string position = "", string location = "", bool useFindJob = false)
        {
            
            
            if (useFindJob == true) { FindByMyJD(id, ref position, ref location);}
            ViewBag.pos = position;
            ViewBag.locate = location;
            System.Diagnostics.Debug.WriteLine(position);
            var listCV = (from CV in db.CVs
                         where (CV.location.Contains(location) && CV.status.Contains("Approved")) 
                         && (CV.applied_position.Contains(position.Trim()) || CV.applicant_name.Contains(position)
                         || position.Trim().IndexOf(CV.applied_position.Trim()) >= 0)
                         select CV).OrderByDescending(model => model.date_upload);
            int pageSize = (size ?? 8);
            int pageNum = page ?? 1;
            return View(listCV.ToPagedList(pageNum, pageSize));
        }


        public ActionResult DetailCV(int id)
        {
            var CV = db.CVs.Where(model => model.CV_id == id).First();
            return View(CV);
        }

        public ActionResult GetPDF(string directory)
        {
            System.Diagnostics.Debug.WriteLine(directory);
            string filepath = "~" + directory;
            return File(filepath, "application/pdf");
        }


        public void FindByMyJD(int id, ref string position, ref string location)
        {
            user cur_user = (user)Session["User"];
            var suitable_JD = (from JD in db.JDs
                               where JD.JD_id == id 
                              select new
                              {
                                  JD.hired_position,
                                  JD.location
                              }).ToList();
            foreach (var item in suitable_JD)
            {
                position = item.hired_position;
                location = item.location;
            }
        }

        public ActionResult ChooseYourJDList(int? size, int? page, string position = "", string location = "")
        {
            user cur_user = (user)Session["User"];
            var list = (from JD_manager in db.JD_managers
                        join JD in db.JDs
                        on JD_manager.JD_id equals JD.JD_id
                        where (JD_manager.user_id == cur_user.user_id && JD.status.Contains("Approved") && JD.isOffered == 0
                        && JD.location.Contains(location)) && (JD.hired_position.Contains(position) || JD.company_name.Contains(position) || JD.JD_name.Contains(position))
                        select new YourJD
                        {
                            JDid = JD.JD_id,
                            JDname = JD.JD_name,
                            JDpos = JD.hired_position,
                            JDlocation = JD.location,
                            dateUpload = JD.date_upload.ToShortDateString(),
                            JDstatus = JD.status,
                            JDoffer = (JD.isOffered == 0)? "Opened" : "Closed",
                            JDimage = JD.company_images,
                            JDcompName = JD.company_name,
                        }).ToList().OrderByDescending(model => model.dateUpload);
            int pageSize = (size ?? 8);
            int pageNum = page ?? 1;
            return View(list.ToPagedList(pageNum, pageSize));
        }


        public ActionResult YourJDList(int? size, int? page, string position = "", string location = "")
        {
            user cur_user = (user)Session["User"];
            var list = (from JD_manager in db.JD_managers
                        join JD in db.JDs
                        on JD_manager.JD_id equals JD.JD_id
                        where (JD_manager.user_id == cur_user.user_id
                        && JD.location.Contains(location)) && (JD.hired_position.Contains(position) || JD.company_name.Contains(position) || JD.JD_name.Contains(position))
                        select new YourJD
                        {
                            JDid = JD.JD_id,
                            JDname = JD.JD_name,
                            JDpos = JD.hired_position,
                            JDlocation = JD.location,
                            dateUpload = JD.date_upload.ToShortDateString(),
                            JDstatus = JD.status,
                            JDoffer = (JD.isOffered == 0)? "Opened " : "Closed",
                            JDimage = JD.company_images,
                            JDcompName= JD.company_name,
                        }).ToList().OrderByDescending(model => model.dateUpload);
            int pageSize = (size ?? 8);
            int pageNum = page ?? 1;
            return View(list.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Detail(int id)
        {
            var JD = db.JDs.Where(model => model.JD_id == id).First();
            return View(JD);
        }

        public ActionResult Delete(int id)
        {
            var JD = db.JDs.Where(model => model.JD_id == id).First();
            var JDmanage = db.JD_managers.Where(model => model.JD_id == id).First();
            db.JD_managers.DeleteOnSubmit(JDmanage);
            db.SubmitChanges();
            db.JDs.DeleteOnSubmit(JD);
            db.SubmitChanges();
            return RedirectToAction("YourJDList");
        }

        //0: if offerd;  1: is not offered
        public ActionResult isOffer(int id)
        {
            var job_offered = db.JDs.First(JD => JD.JD_id == id);
            if (job_offered.isOffered == 0)
            {
                job_offered.isOffered = 1;
            }
            else if (job_offered.isOffered == 1)
            {
                job_offered.isOffered = 0;
            }
            UpdateModel(job_offered);
            db.SubmitChanges();
            return RedirectToAction("Detail",new {@id = id});
        }


        public string ProcessUpload(HttpPostedFileBase fileImage)
        {
            System.Diagnostics.Debug.WriteLine("I'm in processUpload" + fileImage.ToString());
            if (fileImage == null)
            {
                System.Diagnostics.Debug.WriteLine("Is null");
                return " ";
            }
            /*            ViewBag.filePic = "/Content/image/" + fileImage.FileName.ToString();*/
            fileImage.SaveAs(Server.MapPath("~/Content/images/" + fileImage.FileName));
            return "/Content/images/" + fileImage.FileName;
        }


        public ActionResult Edit(int id)
        {
            var cur_JD = db.JDs.First(JD => JD.JD_id == id);
            return View(cur_JD);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection form)
        {
            var cur_JD = db.JDs.First(JD => JD.JD_id == id);
            var JD_nameChanged = form["JD_name"];
            var company_nameChanged = form["company_name"];
            var locationChanged = form["location"];
            var hired_positionChanged = form["hired_position"];
            var position_desChanged = form["position_des"];
            var company_imagesChanged = form["company_images"];
            var JD_fileChanged = form["JD_file"];

            cur_JD.JD_name = JD_nameChanged;
            cur_JD.company_name = company_nameChanged;
            cur_JD.location = locationChanged;
            cur_JD.hired_position = hired_positionChanged;
            cur_JD.position_des = position_desChanged;
            cur_JD.company_images = company_imagesChanged;
            cur_JD.JD_file = JD_fileChanged;
            cur_JD.date_upload = DateTime.Now;
            cur_JD.status = "Wait for justify";
            cur_JD.isOffered = 0;
            UpdateModel(cur_JD);
            db.SubmitChanges();
            return RedirectToAction("YourJDList");
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(FormCollection form, JD cur_JD)
        {
            var JD_nameChanged = form["JD_name"];
            var company_nameChanged = form["company_name"];
            var locationChanged = form["location"];
            var hired_positionChanged = form["hired_position"];
            var position_desChanged = form["position_des"];
            var company_imagesChanged = form["company_images"];
            var JD_fileChanged = form["JD_file"];

            cur_JD.JD_name = JD_nameChanged;
            cur_JD.company_name = company_nameChanged;
            cur_JD.location = locationChanged;
            cur_JD.hired_position = hired_positionChanged;
            cur_JD.position_des = position_desChanged;
            cur_JD.company_images = company_imagesChanged;
            cur_JD.JD_file = JD_fileChanged;
            cur_JD.date_upload = DateTime.Now;
            cur_JD.status = "Wait for justify";
            cur_JD.isOffered = 0;
            db.JDs.InsertOnSubmit(cur_JD);
            db.SubmitChanges();
            return UpdateManageJD();
        }

        public ActionResult UpdateManageJD()
        {
            var model = db.JDs.OrderByDescending(s => s.JD_id).FirstOrDefault();
            JD_manager jD_Manager = new JD_manager();

Trial/Areas/Employer/Views/HomeEmployer/Add.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.5.0/remixicon.css" crossorigin="">
    <link rel="stylesheet" href="~/Content/Employeers access/access/css/cv.css">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/Employeers access/access/css/responsive.css">
    <link rel="stylesheet" href="~/Content/Employeers access/access/font/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Koulen&family=League+Spartan&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fugaz+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chathura:wght@800&display=swap" rel="stylesheet">
    <link rel="icon" href="/image/logo_snkhead.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>
<body>
    <div id="main">
        <div id="header">
            <!-- logo button -->
            <a href="#" class="logo">
                <div class="inner-headings">
                    <span>
                        Job-Seeker<br />
                        Full-Time <br />
                        Part-Time <br />
                        Freelancer <br />
                        Intership <br />
                        Temporary <br />
                    </span>
                </div>
            </a>
            <!-- header - bar -->
            <div class="nav mt-12 ">
                <ul class="sub-nav">
                    <li class="mt-12"><a href="#">@Html.ActionLink("Home", "EmployerFirstPage", "HomeEmployer")</a></li>
                    <li class="mt-12"><a href="">@Html.ActionLink("CV list", "CVlist", "HomeEmployer")</a></li>
                    <li class="mt-12"><a href="#">@Html.ActionLink("Your JD list", "YourJDList", "HomeEmployer")</a></li>
                    <li class="mt-12"><a href="#">@Html.ActionLink("Contact", "Contact", "HomeEmployer")</a></li>
                    <!-- job button -->
                    <button class="bbtn2"><a href="#">@Html.ActionLink("Offer a Job", "Add", "HomeEmployer", new { @style = "color:#fff; text-decoration: none;" })</a></button>
                </ul>
                <!-- Log out statement -->
                <div class="log-out" style="margin-left: 600px">
                    <!-- Name User -->
                    @{
                        var cur_user = (Trial.Models.user)HttpContext.Current.Session["User"];
                        if (cur_user != null)
                        {
                            string name = cur_user.email;
                            <p class="name-user">
                                @name.Split('@')[0]
                            </p>
                        }
                    }
                    <!-- Log out button -->
                    <div class="scene">
                        <div class="cube">
                            <span class="side top">
                                @Html.ActionLink("Are You Sure?", "Logout", "User", new { area = "" }, new { @style = "text-decoration: none; color: white;" })
                            </span>
                            <span class="side front">
                                <i class="fa-solid fa-right-from-bracket"> Log Out</i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- FORM -->
        <div class="form-name">
            <p>Create your CV</p>
        </div>
        <div class="formCV">
            @using (Html.BeginForm())
            {
                <form>
                    <h2>Your JD</h2>
                    <label for="name">JD name:</label>
                    <input type="text" id="name" name="JD_name" placeholder="JD name..." required>
                    <br>
                    <label for="email">Company name:</label>
                    <input type="text" id="email" name="company_name" placeholder="Company name..." required>
                    <br>
                    <label for="education">Hired Position:</label>
                    <input type="text" id="education" name="hired_position" placeholder="Hired position......">
                    <br>
                    <label for="descip">Desciption:</label>
                    <textarea class="form-control" id="descip" type="text" name="position_des" placeholder="Tell more about the position..." data-sb-validations="required"></textarea>
                    <br>
                    <div class="location">
                        <label class="local-name" for="lname">Location:</label>
                        <select name="location" id="location-job">
                            <option value="HCM">HCM</option>
                            <option value="Hanoi">Hanoi</option>
                        </select>
                    </div>
                    <!-- UpLoad File and img -->
                    <label for="file_img" class="upfile">Upload your company image here:</label>
                    <input type="file" id="file_img" class="upfile" accept="image/*">
                    <input type="hidden" name="company_images" id="directory_img" />
                    <br />


                    <label for="file_pdf" class="upfile">Upload your JD file here:</label>
                    <input type="file" id="file_pdf" class="upfile" accept=".pdf, image/*">
                    <input type="hidden" name="JD_file" id="directory_pdf" />
                    <button class="mtn"><span>Submit</span></button>

                </form>
            }

        </div>

    </div>
    <!-- Footer -->
    <div id="FooterPage">
        <footer>
            <div class="container text-center text-md-left col-third">
                <div class="footer-wrap">
                    <div class="about">
                        <img src="img/icon/company-logo.svg" alt="">
                        <p class=" py-4" style="font-weight: 500; margin-top: -33px;">About</p>
                        <p class="text-muted py-4">
                            Job-Seeker which can provide you with all the tools </br> needed to run an effcieint business remotely.
                        </p>
                        <div class="social-media">
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/facebook-icon.svg" alt=""></a>
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/instagram-icon.svg" alt=""></a>
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/linkedin-icon.svg" alt=""></a>
                            <a href="" class="me-2 text-reset"><img src="~/Content/Applicant access/access/img/icon/email-icon.svg" alt=""></a>
                        </div>
                    </div>

                    <div class="company  ">
                        <h6 class="fw-bold">Company</h6>
                        <p><a href="./contact.html">Contact</a></p>
                        <p><a href="">Blog</a></p>
                        <p><a href="">Services</a></p>
                        <p><a href="">FQA</a></p>
                    </div>

                    <div class="useful-links  ">
                        <h6 class="fw-bold">Useful links</h6>
                        <p><a href="">Terms of </a></p>
                        <p><a href="">Services</a></p>
                        <p><a href="">Privacy Policy</a></p>
                        <p><a href="">Documentation</a></p>
                        <p><a href="">Changelog</a></p>
                        <p><a href="">Components</a></p>
                    </div>

                    <div class="newsletter  ">
                        <h6 class="fw-bold">Have a Question?</h6>
                        <p><i class="fa-solid fa-location-dot"></i>203 Fake St. Mountain View, San Francisco, California, USA</p>
                        <p><i class="fa-solid fa-phone"></i> 84+ 0935459488</p>
                        <p><i class="fa-solid fa-envelope"></i> kienphongtran2003@gmail.com / buikhoa2015@gmail.com  </p>
                    </div>

                </div>
                <div class="copyright txtwhite">
                    <p>&copy; 2023 JOB-SEEKER | Created by Phong / Khoa</p>
                    <!--
                    This template is licenced under Attribution 3.0 (CC BY 3.0 PL),
                    You are free to: Share and Adapt. You must give appropriate credit, you may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
                    -->
                </div>
            </div>

        </footer>
    </div>
    <script>
        $(document).ready(function () {
            //Image
            $('#file_img').click(function () {
                console.log("You Click Img");
                $('#file_img').change(function () {
                    console.log("You change Img");
                    if (window.FormData !== undefined) {

                        var fileUpload = $('#file_img').get(0);
                        var files = fileUpload.files;
                        var formData = new FormData();
                        formData.append("fileImage", files[0]);
                        //formData.append("fileImage", files[0]);
                        /*for (var i = 0; i < files.length; i++) {
                            formData.append("fileImage", files[i]);
                        }*/
                        $.ajax(
                            {
                                type: 'POST',
                                url: '/HomeEmployer/ProcessUpload',
                                contentType: false,
                                processData: false,
                                data: formData,
                                success: function (urlImage) {
                                    console.log(urlImage);
                                    $('#directory_img').attr('value', urlImage);
                                    $('#picture').val(urlImage);
                                },
                                error: function (err) {
                                    alert('Error ', err.statusText);
                                }
                            });
                    }
                });

            });



            //Pdf
            $('#file_pdf').click(function () {
                console.log("You Click PDF");
                $('#file_pdf').change(function () {
                    console.log("You change PDF");
                    if (window.FormData !== undefined) {

                        var fileUpload = $('#file_pdf').get(0);
                        var files = fileUpload.files;
                        var formData = new FormData();
                        formData.append("fileImage", files[0]);
                        //formData.append("fileImage", files[0]);
                        /*for (var i = 0; i < files.length; i++) {
                            formData.append("fileImage", files[i]);
                        }*/
                        $.ajax(
                            {
                                type: 'POST',
                                url: '/HomeEmployer/ProcessUpload',
                                contentType: false,
                                processData: false,
                                data: formData,
                                success: function (urlImage) {
                                    console.log(urlImage);
                                    $('#directory_pdf').attr('value', urlImage);
                                    $('#picture').val(urlImage);
                                },
                                error: function (err) {
                                    alert('Error ', err.statusText);
                                }
                            });
                    }
                });

            });

        });
    </script>
</body>
</html>